# Generated by Django 3.1.6 on 2021-05-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
