# Generated by Django 3.1.6 on 2021-05-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210509_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
